package com.cloudnotes.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    DUPLICATE_EMAIL,
    RESOURCE_NOT_FOUND,
    DUPLICATE_TAG,
    UNSUPPORTED_FILE_TYPE,
    FILE_TOO_LARGE,
    EMPTY_FILE,
    STORAGE_ERROR,
    INVALID_TOKEN,
    RATE_LIMIT_EXCEEDED,
    BAD_REQUEST,
    CONFLICT,
    INTERNAL_ERROR
}
